### ISSUE TITLE
helm chart repo already exists should not error fatal

### ISSUE THREAD

**Issue by gmodzelewski** [redhat-na-ssa/redhat-developer-hub-gitops-bootstrap#3]
The ansible playbook stops with a fatal error, if the helm chart repository already exists. Removing the existing repo solves the exiting playbook. 

I'm not really firm in ansible, but I suppose something like that here would help and stop the playbook to exit with an error.

```yaml
- name: Add Helm repository
      kubernetes.core.helm_repository:
        name: your_repo_name
        repo_url: your_repo_url
        state: present
      register: helm_repo_result
      ignore_errors: true

    - name: Display warning if repository already exists
      debug:
        msg: "Helm repository '{{ your_repo_name }}' already exists. Skipping addition."
      when: helm_repo_result|failed
```
