### ISSUE TITLE
root app vault components don't sync due to source.directory.recurse = false mismatch

### ISSUE THREAD

**Issue by alexgroom** [redhat-na-ssa/redhat-developer-hub-gitops-bootstrap#5]
After installing the gitops server and components using ./bootstrap-scripts/cluster-boostrap.sh I find that the root app remains "outOfSync" due to a mismatch between live and desired manifest. This applies to vault, vault-config and vault-config-operator sub applications.

The Vault operator is 0.8.25
Argo is 2.9.5+f943664
OpenShift 4.14.11

The diff reports that the mismatch is source.directory.recurse=false which is defined in the desired manifest

```
  project: default
  source:	  source:
    directory:
      recurse: false
```
